[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "demo-mcp"
version = "0.1.0"
description = "A demo MCP server for Figma → Code translation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=0.3.0",
]

# ✅ 定义命令行脚本
[project.scripts]
demo-mcp-server = "demo_mcp.server:main"

# ✅ 声明包结构
[tool.setuptools.packages.find]
where = ["src"]
include = ["demo_mcp*"]

[tool.setuptools.package-dir]
"" = "src"