[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "demo-mcp-server"
version = "0.1.0"
description = "Minimal MCP (Model Context Protocol) Server Demo"
requires-python = ">=3.8"
dependencies = [
    "mcp-server>=0.2.0",
    "uvicorn"
]

[project.scripts]
demo-mcp-server = "demo_mcp:main"
