[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "demo-mcp-server"
version = "0.1.0"
dependencies = [
    "mcp>=1.18.0",  # ✅ 官方 MCP SDK（支持 server 模式）
    "uvicorn>=0.27.0",
    "starlette>=0.32.0",
]
